### ISSUE TITLE
Add liveness & rediness endpoints to the project

### ISSUE THREAD

**Issue by yonatankarp** [yonatankarp/beat-the-machine#6]
As the project would be deployed, we would like to ensure that the service is alive, and if not, allow the host to restart it.

The dependency for it is already in the project as part of the spring boot template, but I need to configure it in the `application.yaml` file as follows:

```yml
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - metrics-requiredMetricName
          - prometheus
          - loggers
          - health
          - httptrace
  endpoint:
    health:
      probes.enabled: true
      show-details: always
      livenessState.enabled: true
      readinessState.enabled: true
    metrics.enabled: true
    prometheus.enabled: true
    metrics:
      export.prometheus.enabled: true
      distribution:
        percentiles-histogram.http.server:
          requests: true
        sla.http.server.requests: 50ms, 100ms, 200ms, 400ms
        percentiles.http.server:
          requests: 0.5, 0.9, 0.95, 0.99, 0.999
```
